### ISSUE TITLE
Not really an issue more a question (restore data for new system)

### ISSUE THREAD

**Issue by dannymertens** [pinkywafer/Anniversaries#100]
Hi Jenny,

First my biggest congratulations and thanks for all the work you put in to this, also from the family who love to get a TTS, notification for new birthdays, anniversaries on their mobile!

Now I just got myself a Blue device and after years of playing, testing things I think it's time for a new start so set up a complete new configuration (no snapshot restore) without all the ballast that probably is lurking in my old system ;-)

One of the last things to do is setting up your addon, no way I can shutdown the old system before this, now I added quite a lot of birthdays, anniversaries in your config true the integrations part of your app, and well to be honest don't looking forward to do this again, and even lost some information I'm afraid, so is there an option to copy the data in the addon, and restore it in the new system, or at least export a list of all the birthdays, events I have in my old system ?

**Old current production system**

System Health

version: core-2021.2.3
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.7
os_name: Linux
os_version: 5.4.94
arch: x86_64
timezone: Europe/Brussels
host_os: Home Assistant OS 5.11
update_channel: stable
supervisor_version: supervisor-2021.02.9
docker_version: 19.03.13
disk_total: 97.7 GB
disk_used: 17.9 GB
healthy: true
supported: true
board: ova
supervisor_api: ok
version_api: ok
installed_addons: Visual Studio Code (3.1.0), MariaDB (2.2.1), phpMyAdmin (0.2.0), Samba share (9.3.0), Home Assistant Google Drive Backup (0.103.1), SSH & Web Terminal (8.0.1), File editor (5.2.0), Mosquitto broker (5.1), Eufy Home Assistant MQTT Bridge (1.11.0)

**New system**

System Health

version: core-2021.2.3
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.7
os_name: Linux
os_version: 5.9.16
arch: aarch64
timezone: Europe/Brussels
host_os: Home Assistant OS 5.11
update_channel: stable
supervisor_version: supervisor-2021.02.11
docker_version: 19.03.13
disk_total: 113.9 GB
disk_used: 26.4 GB
healthy: true
supported: true
board: odroid-n2
supervisor_api: ok
version_api: ok
installed_addons: Samba share (9.3.0), Visual Studio Code (3.1.0), deCONZ (6.7.2), MariaDB (2.2.1), Samba Backup (4.4), InfluxDB (4.0.3), Grafana (6.1.2), SSH & Web Terminal (8.0.3), Assistant Relay (0.7.4)

Thanks in advance!

Kind regards,

Danny

**Comment by pinkywafer** [comment]
Sadly there's no way to export and import this data from one setup to another, but you can get a list of all the sensors configured  and their dates by using the Developer tools, template page:
paste in this template:
```
{% for state in states.sensor -%}
  {%- if state.attributes.attribution == "Sensor data calculated by Anniversaries Integration" -%}
    {{state.attributes.friendly_name}}: {{state.attributes.date}}
  {% endif -%}
{%- endfor %}
```
and you should get a list of the configured anniversaries friendly names and dates.
You can then copy / paste this into any text editor to use for your reference

**Comment by dannymertens** [comment]
Hi,

Thanks! Was hoping that I didn't had to do it again ;-) but now I have a least a clean list to follow so stil happy with i!

If possible I would like to put in a new feature request for a backup/restore function, because I'm probably not the only person who has run in to this, of course if it's possible, I'm not a developer so to be honest don't even know if this is an option, but asking hurts nobody off course :-)

Thanks for your quick reply!!!

**Comment by pinkywafer** [comment]
I have been thinking about this, and have decided that I am not going to be implementing any backup/restore functionality (at least for the time being). I feel that it is an edge case that it would be useful for, the more likely being the use of snapshots to restore. Those who use configuration.yaml would alse have no need for the feature either.
