### ISSUE TITLE
reporting an issue

### ISSUE THREAD

**Issue by haddood** [pinkywafer/Anniversaries#102]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:371
First occurred: 3:24:28 PM (1 occurrences)
Last logged: 3:24:28 PM

Updating state for sensor.anniversary_name_day (<class 'custom_components.anniversaries.sensor.anniversaries'>) took 0.575 seconds. Please report it to the custom component author.

**Comment by pinkywafer** [comment]
unable to replicate.  Can you provide any further information please

**Comment by pinkywafer** [comment]
closing as no further info
