### ISSUE TITLE
Remove the anniversary integration 

### ISSUE THREAD

**Issue by sjude68** [pinkywafer/Anniversaries#103]
How do I remove the anniversary integration. I deleted the directory from custom_integration and the section from configuration.yaml file and restarted home assistant. I got error that anniversary integration not found but in configuration -> integration the sensors are showing. How to completely remove.

**Comment by pinkywafer** [comment]
As with any integrations that can be set up using the config flow, if you have set up using the config flow (UI), you must remove the entities BEFORE deleting the integration.  The methods to add / remove an integration via the config flow are contained within the custom component.

Your easiest method now would be to reinstall the custom component via hacs (or replace the deleted folder), remove the configured entities via the config flow, then remove the folder.

**Comment by sjude68** [comment]
Thanks @pinkywafer for your reply. I re-copied the deleted folder and then deleted the integration.
