### ISSUE TITLE
no integration

### ISSUE THREAD

**Issue by peterdierckx2840** [pinkywafer/Anniversaries#109]
HACS integration works fine but didn't find Anniversaries in Configuration/Integrations
using. core-2021.9.6. supervisor-2021.09.0

**Comment by pinkywafer** [comment]
If it has installed fine with hacs, make sure to refresh your browser (ctrl-F5 in chrome). The integrations list is stored in browser cache, so needs the refresh.

**Comment by peterdierckx2840** [comment]
Hello Jenny

Thanks for your reply
Feedback: refreshed several times the browser cache without any result
Then I tried to add  anniversaries:  in my config file and I got
 
as a result after restart…. BUT integration was present and working
I removed.  anniversaries: from config file and everything is working now

Best regards

Peter
