### ISSUE TITLE
Ability to add "days until" before the number in UI

### ISSUE THREAD

**Issue by yuvalabou** [pinkywafer/Anniversaries#11]
formatting the sensor to allow more convinient look.
something like 
"days until {days}"
or
"{days} more days"

**Comment by pinkywafer** [comment]
I'll add this as a config option when I get chance!

**Comment by pinkywafer** [comment]
Rather than adding a separate config option, I think I'm just going to add `days` as the unit of measurement. This way, if a badge is displayed, it will show the number in the circle,  with a days label, and if displayed on an entities card it would say `xx days`

**Comment by yuvalabou** [comment]
I agree 👍
