### ISSUE TITLE
Date change doesn't happen at midnight (timezone?)

### ISSUE THREAD

**Issue by gorillica** [pinkywafer/Anniversaries#110]
Hi, I’m in Sydney, which is currently GMT+11 because of DST. I have a countdown set up using Anniversaries, but have noticed that the countdown doesn’t change until 11am here (midnight GMT). Everything else in Home Assistant shows the correct time zone (including Recorder entries). I can't see an obvious way to specify the time zone in the sensor configuration.

Is this fixable? Thanks! I wonder if it’s related to the issue being discussed at #106.

<img width="395" alt="Screen Shot 2021-10-14 at 9 38 58 am" src="https://user-images.githubusercontent.com/1840636/137222331-73d1cb2e-bd24-4293-890a-9f81b3fe5495.png">

**Comment by pinkywafer** [comment]
Thanks.  I believe this may be related, but I'll leave it as two separate issues for now.

Can you please try the `timezone-fix-beta` release and let me know if that solves it? - For manual install, you only need the sensor.py from the [timezone-fix-test](https://github.com/pinkywafer/Anniversaries/tree/timezone-fix-test) branch.
To do hacs install, go to hacs and find the anniversaries integration.  Click the menu (3 dots).  Choose `Redownload`.  Ensure `Show beta versions` is turned on and choose the `timezone-fix-beta` release.  You'll need to reboot Home Assistant

**Comment by pinkywafer** [comment]
unrelated issue.
so...
I'm going to take a guess that this is system specific - can you tell me about your install.
I've been able to replicate similar when having HA timezone different to OS timezone

**Comment by gorillica** [comment]
I’m away from home for a couple of weeks, but when I get back I’ll try the `timezone-fix-test` branch. Then I’ll report back here: thanks!

I’m running HA Container in Docker, on an Ubuntu host system.

**Comment by gorillica** [comment]
I updated `sensor.py` to the version in the `timezone-fix-test` branch yesterday. When I went to check my sensor this morning, it hadn’t updated at midnight.

My Docker container has the right timezone: I have `TZ="Australia/Sydney"` as an environment variable in my Docker Compose file.

**Comment by pinkywafer** [comment]
Time zone is not configurable in the sensor, as it is not used for calculation.  The date uses the Python date.today() function. This gets the date from the system without any timezone information. This is then compared with the configured date.  The only way I have been able to get this to be off is for the system's and Home Assistant's time zones to be different to each other.  However, a previous home assistant update made the time displayed in the graph use the browser's configured time zone, so check that the timezone on the device you're accessing the frontend is the same timezone and also check that the clock on that device is correct.
Also try the latest release as it is newer than the branch
