### ISSUE TITLE
Question about date_template formatting?

### ISSUE THREAD

**Issue by knissdesign** [pinkywafer/Anniversaries#112]
Hello, I am super excited to get started with Anniversaries! For the life of me, though, I cannot figure out how to use the date_template config. Perhaps an example could be dropped in the example config block?

**Comment by pinkywafer** [comment]
at the moment, the date template needs to have a string for the date (this may change in the future as native types are now supported in home assistant)
so for now, you need to explicitly tell the template to return a string, ie:
``` yaml
date_template: '{{ states("input_datetime.your_input_datetime") | string }}'
```

Agree - I'll add this to the examples at the next release
