### ISSUE TITLE
Speaking counter

### ISSUE THREAD

**Issue by deeg61** [pinkywafer/Anniversaries#113]
I love this ad one and want to thank you for your hard work. I'm curious if it's possible is to make an adjustment to let the counter, by notify speaks the day's left. So, for example, that a kid hears on the speaker every day at a certain time how many days are left for his or her birthday. Thank you in advance for your time

**Comment by pinkywafer** [comment]
you can use a simple automation for this.
use a time trigger - select what time you want the notification.  For the action, choose call service, then your notify platform for the action. and for the message, use something like : `It's only {{states("sensor.anniversary_your_birthday_sensor")}} days until your birthday`

**Comment by deeg61** [comment]
Thank you Jenny for the quick response. I’ve tried it out and it works Your the best !!!! RegardsRob Verzonden vanuit Mail voor Windows Van: JennyVerzonden: vrijdag 7 januari 2022 18:46Aan: pinkywafer/AnniversariesCC: deeg61; AuthorOnderwerp: Re: [pinkywafer/Anniversaries] Speaking counter (Issue #113) you can use a simple automation for this.use a time trigger - select what time you want the notification. For the action, choose call service, then your notify platform for the action. and for the message, use something like : It's only {{states("sensor.anniversary_your_birthday_sensor")}} days until your birthday—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
