### ISSUE TITLE
Date template not showing correctly 

### ISSUE THREAD

**Issue by tamimology** [pinkywafer/Anniversaries#115]
After the uodate all dates are not showing as DD-MM-YYYY

Before I used to define using date_format: '%a %b %d, %Y' and it was wonderful.

What happened now! 
![Screenshot_20220112-133122_Home Assistant](https://user-images.githubusercontent.com/90429593/149053615-8e7ca6b1-b04c-47c5-b9b4-49b71f0524be.png)

**Comment by pinkywafer** [comment]
I'm afraid that this is intended.  The date is now returned as a native date time and the date_format option is deprecated.

This change has been brought about by the Lovelace frontend becoming 'smarter'. Anything which it considered to be a date was automatically formatted, thereby rendering many 'standard' formats useless, and it also introduced an issue - my date attribute had no time zone information (none was needed), but with Lovelace now auto formatting most dates, Lovelace assumed all dates were UTC and converted the display to local timezone, thereby making the date wrong for many.
Returning a datetime with the timezone included and removing the date_format option was the only way to work around this as a standard.
As you appear to be using multiple-entity-row for your anniversaries, there are options as part of that which allow formatting the date.
I'm using:
```yaml
secondary_info:
  attribute: date
  format: date
```
Sadly this is not customizable though.

**Comment by tamimology** [comment]
Fair enough

Still prefer to have it customised but at least you got a way with it. I think if it was using the official entity card then it wouldn't be changed.

**Comment by Borcon** [comment]
Here is my example - dynamic card, sorted by date:

![image](https://user-images.githubusercontent.com/39000945/156639998-783c47c7-2bdb-4743-aec9-19caf53180ae.png)

card:
  show_header_toggle: false
  title: Jahrestage
  type: entities
filter:
  include:
    - entity_id: sensor.anniversary*
      options:
        secondary: >
          {{ state_attr(config.entity,'date') | replace('00:00:00+02:00','') | replace('00:00:00+01:00','') }}
          - {{ state_attr(config.entity,'years_at_next_anniversary')}} Jahre 
        state: |
          {{ states(config.entity) }} Tage
        type: custom:template-entity-row
sort:
  method: state
  numeric: true
type: custom:auto-entities
