### ISSUE TITLE
Request: Set own defaults

### ISSUE THREAD

**Issue by oblivionratula** [pinkywafer/Anniversaries#117]
Would be nice to be able to set our own global default for things like days_as_soon or icons instead of having to define them for every entry (e.g. if I want 'soon' to bee one week 99% of the time).  Not a big deal to copy/paste in configuration.yaml, but if entering from Intergrations page, it's a little tedious.  Sorry if it's already possible and I missed it.

Thanks for considering this, and thanks for the work thus far.

**Comment by pinkywafer** [comment]
I think this is one of those cases where I'm not sure this can be implemented at all, let alone easily. I believe it would need an entity set up first to change the default, then pobably a restart to enable these to be loaded by the config flow. Also, as most users only set up the anniversaries once, it then ceases to be useful again.  If you know that you want to set up a lot of anniversaries with a particular edfault, you could edit the `DEFAULT_SOON =1` line in the `const.py` file, restart home assistant, then set up all your entities.  it would be overwritten in any updates, but you would already have your entities set up.
