### ISSUE TITLE
Request: Change icon color

### ISSUE THREAD

**Issue by sycorhsx** [pinkywafer/Anniversaries#122]
I really like the tool, but I'd love it it were possible to set the icon color.  I'm fairly new to HA and everything but not having to edit a theme just to change the icon color would be great.

**Comment by Kilowatt-W** [comment]
This would really be a nice Feature something like 👍 
iconcolor: RED

Thx

KW

**Comment by pinkywafer** [comment]
This is beyond the scope of the integration.  the icons colors are not controlled by the integration (the backend) the color is controlled by the front end, so you eithe need to alter the theme, or use a (custom) card which allows color control
