### ISSUE TITLE
Issue after HA 22.10.1 update.

### ISSUE THREAD

**Issue by sheminasalam** [pinkywafer/Anniversaries#123]
I get the following error in logs and the component is not loaded.

```
Logger: homeassistant.setup
Source: setup.py:192
First occurred: 6:43:03 AM (2 occurrences)
Last logged: 6:43:07 AM

Setup failed for custom integration anniversaries: Unable to import component: cannot import name 'CC_STARTUP_VERSION' from 'integrationhelper.const' (/usr/local/lib/python3.10/site-packages/integrationhelper/const.py)
```

**Comment by pinkywafer** [comment]
Caused by chane in HA.  I'll get on it!

**Comment by pinkywafer** [comment]
Actually, further testing here is showing that it is still working on my installs, but I'll remove the integrationhelper stuff anyway as it is not really needed

**Comment by sheminasalam** [comment]
I am runnning supervised installation in rpi4 with raspbian.

**Comment by Roger-The-Paradox** [comment]
Thank you for the integration.  It has saved my bacon a few times (Who remembers their own wedding anniversary?)

**Comment by pinkywafer** [comment]
Assuming this has resolved itself? - Please re-open if not.  The integrationhelper stuff should be installed by Home Assistant, if it's not working, try restarting home assistant.  The integration helper is needed, so will not remove
