### ISSUE TITLE
Not recognized

### ISSUE THREAD

**Issue by mcnguyen33r** [pinkywafer/Anniversaries#127]
Logger: homeassistant.setup
Source: setup.py:202
First occurred: August 7, 2022 at 8:33:32 PM (1 occurrences)
Last logged: August 7, 2022 at 8:33:32 PM

Setup failed for custom integration anniversaries: Requirements for anniversaries not found: ['integrationhelper>=0.2.2'].

**Comment by apaperclip** [comment]
Can you provide more information? How did you install, HA version etc?

I just did a fresh clone of this repo to a 2023.2.0 HA install with no errors

**Comment by pinkywafer** [comment]
Unable to reproduce.

Please provide details of your setup.  the 'integrationhelper' is requirement of a lot of integrations and should be installed with HA

**Comment by pinkywafer** [comment]
Additional: if it is still not working, try restarting Home assistant as this should install the integrationhelper

**Comment by pinkywafer** [comment]
unable to replicate and no further information given
