### ISSUE TITLE
Feature idea - integration with Google calendar

### ISSUE THREAD

**Issue by apaperclip** [pinkywafer/Anniversaries#128]
Anniversaries has been great for the years I've used it but I've always wanted to the drive data for it from a shared google calendar.  Now that HA has improved google calendar support I thought there would be an opportunity to either move away from Anniversaries or see some type of combination of the two.

The issue I'm running into is how to get the event data from google calendar as unique entities so they can be displayed on a dashboard, calculations run against it, etc. but without manual configuration for each event. 

For example, I could create a calendar entity using the search/filter feature to uniquely match each event I want to to track, but when new events are added to the shared calendar, I have to manual create a calendar entity for each new event.   Or, if I use the calendar trigger for an automation, I can't find a way to get that data from the automation to an entity for dashboard purposes.  There is also the added challenge of multiple all-day events in the calendar.  I'm pretty sure the calendar trigger is the only way to see info about each event as an entity in HA today.  These methods do not scale and are cumbersome.

Would there be an opportunity for Anniversaries to be the glue here.  Could it leverage the google calendar integration, select a calendar(s) of interest and create entities for those events? This would enable HA to dynamically create/delete entities for events, management of HA cal entities outside of HA/Anniversaries, and even distributed mgmt. with a shared calendar.  

My particular use case is a shared google calendar with ~60 birthday and anniversaries with more being added.

What does everyone think? Am I missing some way to do this today?  Would this be useful to others?

**Comment by pinkywafer** [comment]
Interesting idea, and may be worth looking into.

**Comment by pinkywafer** [comment]
I've decided Im not going to add this:
1. This integration was always intende to be local and not rely on any external cloud connection
2. If any external calendar support was added, I would then expect other users to want other calendar providers to be added as well and the integration would balloon

**Comment by apaperclip** [comment]
Ok, Thank you for the consideration and reply.
