### ISSUE TITLE
make unit of measurement translatable 

### ISSUE THREAD

**Issue by SebRut** [pinkywafer/Anniversaries#13]
It would be nice to be able to translate the unit to as "days" is pretty much the only thing visible most of the time

**Comment by pinkywafer** [comment]
I'm going to have to look into how to achieve this.  I believe various units of measurement are translate-able by the frontend, so will look into that first

**Comment by pinkywafer** [comment]
Reference:
https://developers.home-assistant.io/docs/en/internationalization_backend_localization.html
https://developers.home-assistant.io/docs/en/internationalization_custom_component_localization.html

**Comment by pinkywafer** [comment]
Sadly I'm going to have to close this as I've had confirmation from @balloob (HA founder) that this is not possible.
I'll revisit this if this is ever implemented

**Comment by balloob** [comment]
FYI, if you make the sensor output an iso8601 formatted timestamp as the state and use the [timestamp device class](https://developers.home-assistant.io/docs/en/entity_sensor.html#available-device-classes), you can have Lovelace count down for you using the entity row [`format`](https://www.home-assistant.io/lovelace/entities/#format) option.

**Comment by pinkywafer** [comment]
thanks. @balloob I dont really want to go down that route though - trying to keep the sensor set up as simple as possible.

**Comment by pinkywafer** [comment]
I am re-opening this though... I have an idea!....

**Comment by pinkywafer** [comment]
ok, I'm not happy with any of the options I have tried, so I'm going to close this for now.
I will revisit this if it becomes possible in the future.
I would suggest that in the meantime you use a customize to customize the `unit_of_measurement`
ie..
in customize.yaml
```
sensor.name_of_sensor:
  unit_of_measurement: Days
```
(replace Days with your translation)
