### ISSUE TITLE
Just updated HA and log says issue with anniversaries

### ISSUE THREAD

**Issue by mrfearless** [pinkywafer/Anniversaries#130]
Logger: homeassistant.setup
Source: setup.py:213
First occurred: 9:58:31 PM (1 occurrences)
Last logged: 9:58:31 PM

Setup failed for custom integration anniversaries: Unable to import component: cannot import name 'CC_STARTUP_VERSION' from 'integrationhelper.const' (/usr/local/lib/python3.10/site-packages/integrationhelper/const.py)

I completely restarting my HA machine and still getting this message. Only appeared after updating home assistant core. Maybe something broke somewhere.

Home Assistant 2023.2.5 
Supervisor 2023.01.1 
Operating System 9.5 
Frontend 20230202.0 - latest

**Comment by pinkywafer** [comment]
No such issue after updating on mine, but I suggest you try restarting home assistant a time or two and see if it cures itself... It seems that home assistant installs the 'integrationhelper' at startup, so the update can overwrite this, and then it reinstalls the latest version after.  If that doesn't cure it, let me know more about your installation type etc.
Thanks

**Comment by mrfearless** [comment]
Didn't seem to make any difference, tried numerous times to just restart the whole hardware box, still same issue. Had to use Terminal and SSH addon to map a network share to /config on the HA machine. Then i could navigate to .storage folder and edit core.config_entries using notepad++ (took backup beforehand), then i was able to delete all anniversary entries. Saved file, restarted HA. Also uninstalled Anniversaries from HACS. Problem has now been resolved.
