### ISSUE TITLE
An error occurred while processing

### ISSUE THREAD

**Issue by aptonline** [pinkywafer/Anniversaries#20]
Not sure if this is a Anniversaries error or related to HACS but seeing the following when attempting to update:

![A0E85D42-7584-40CE-9517-F1567141BDB2](https://user-images.githubusercontent.com/190136/72458975-98ccdd00-37c1-11ea-9757-6cc6085d34d4.png)

**Comment by pinkywafer** [comment]
I believe this is HACS related, but can't say what the issue is.  I can definately tell you that both my HA instances updated fine through HACS, and the anniversaries repo shows 29 succesful downloads since the update only a few minutes ago.  
Might be worth trying a restart of Home Assistant

**Comment by aptonline** [comment]
Restart seems to have resolved it, if it re-occurs I’ll pass the issue onto @ludeeus.

**Comment by ludeeus** [comment]
Its neither, "session is closed" is a transport (network) error.

**Comment by pinkywafer** [comment]
Thanks for clarifying @ludeeus
