### ISSUE TITLE
Issue with dates more than a year away

### ISSUE THREAD

**Issue by Shaun-Harrison** [pinkywafer/Anniversaries#23]
Hello

I know this is an anniversary card so may be out of the scope of the project
But if a date that I'm tracking is over a year away it will show the countdown as if its the same year
For example ; 

![image](https://user-images.githubusercontent.com/46562010/72645129-c7d28280-396a-11ea-9bd1-e59b6eceb5ec.png)

The countdown shows there are 322 days but that is until its one year away - ideally this would show as 687 days

**Comment by pinkywafer** [comment]
It is beyond the original scope, but I can certainly add it!
