### ISSUE TITLE
Translate unit_of_measurement. Possible??

### ISSUE THREAD

**Issue by ricreis394** [pinkywafer/Anniversaries#24]
I use home assistant in another language but english. Is it possible or correct to have a translation of the unit_of_measurement?

I had like to have "dias" instead of "days".

**Comment by pinkywafer** [comment]
This has come up before, and it is not possible at the moment to auto translate unit of measurement, 
BUT...
You can change the unit of measurement with a customization: 
There are two ways to do this:
1. In customize.yaml:
```yaml
sensor.your_sensor_id:
  unit_of_measurement: Dias
```
Or you can use the Customizations from the Configuration menu:
Select your sensor, under "Pick an attribute to override" select unit_of_measurement, then type Dias in the box

**Comment by ricreis394** [comment]
Ok thanks. That's great!

**Comment by pinkywafer** [comment]
reopening - solution should be added to docs
