### ISSUE TITLE
Package anniversaries setup failed. Integration anniversaries No module named 'integrationhelper' (See /config/packages/anniversaries.yaml:0). 

### ISSUE THREAD

**Issue by hunleyd** [pinkywafer/Anniversaries#27]
Somewhere in the 0.104.x or 0.105.x I started getting this message in my logs. Did I miss something in my config during an upgrade or did recent HA break anniversaries?

**Comment by pinkywafer** [comment]
I have not seen this issue, but I have heard of it on other custom components. 
The integrationhelper should be installed by homeassistant at startup, so it may have got 'lost' somewhere in the upgrades.
Apparently, the solution is just to restart Home Assistant a couple of times and it should resolve itself
