### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by casimiroc** [pinkywafer/Anniversaries#30]
Hi here are the French translation of Anniversaries, I hope it help someone.

Thank you
[fr.json.zip](https://github.com/pinkywafer/Anniversaries/files/4216807/fr.json.zip)

**Comment by pinkywafer** [comment]
Thank you!

**Comment by casimiroc** [comment]
You welcome and let know if it’s good so I can go for the Portuguese. 

Cordially 



  
----------------------------------------------

**Comment by pinkywafer** [comment]
Looks good!   I have committed the file and released with it included.
If you can, the Portuguese would be great too! 

Thanks again!

**Comment by casimiroc** [comment]
would it be possible to include in the translation file the following variables "day" and "Days"?  Otherwise these variables will always be in English.

Thanks

**Comment by pinkywafer** [comment]
See the [Notes on unit of measurement section of the readme](https://github.com/pinkywafer/Anniversaries/blob/master/README.md#notes-about-unit-of-measurement)
