### ISSUE TITLE
Glance pop up graph

### ISSUE THREAD

**Issue by DrSpaldo** [pinkywafer/Anniversaries#31]
Hi, I couldn't find any forum thread for this. So sorry if this is the wrong spot. 

I was wondering how I can use/modify Anniversaries in my glance card pop up. Currently it shows a graph for the last 24 hours of the day. Is there any way you can increase this to display something different? Ie. Longer period of time or something better?
![screenshot 2020-02-23](https://user-images.githubusercontent.com/8526509/75101286-7767d800-562e-11ea-93a6-7eabc81e86fb.png)

**Comment by pinkywafer** [comment]
The more info pop up is automatically generated by home assistant,  and will always display a graph of the last 24 hours. The best solution is to replace it with something else. I'd recommend the browser_mod plugin by @thomasloven which is available in hacs by default

**Comment by DrSpaldo** [comment]
Thanks for the quick reply @pinkywafer . I've had a look at the plugin, I just can't work out when reading the readme/instructions as to how you would do it :(

**Comment by pinkywafer** [comment]
Right at the bottom of the reader is the [replacing more-info dialogs](https://github.com/thomasloven/hass-browser_mod/blob/master/README.md#replacing-more-info-dialogs) section. 

The second code example in this section is the relevant part. And that `popup_cards` section is at the base of the yaml (same level as `views` and `resources` so not defined in views.

The videos I did about hacs, and my anniversaries and calendarific are going to become the first couple of videos in a 'custom components' playlist,  so I'll be taking a closer look at this in a video before long (I think browser_mod will need a few videos as it is a big and very powerful component!

**Comment by DrSpaldo** [comment]
Thanks. It sure does look like it has quite a bit in it. I will keep reading. I added the example you mentioned and changed it to my birthday sensors but I am getting an error. Must be doing something wrong 
![screenshot 2020-02-23](https://user-images.githubusercontent.com/8526509/75109391-870b0f00-5676-11ea-99e0-1dab31e53ac9.png)

**Comment by pinkywafer** [comment]
Try:
```yaml
type: history-graph
entities:
  - sensor.lucy_s_birthday

**Comment by pinkywafer** [comment]
Down side would be,  history-graph defaults to 24 hours. You can change using: `hours_to_show` but the maximum is 80 hours, so may still not be very useful!

**Comment by DrSpaldo** [comment]
Yeah, 80 hours doesn't have much use. Maybe I will just not worry about it then and try to ignore the graph :)

**Comment by pinkywafer** [comment]
my only thought would be to use an entity-attribute-card. 
I'm going to look at changin default more-info in my next video!

**Comment by pinkywafer** [comment]
see https://youtu.be/atpIP2RYldA
