### ISSUE TITLE
translations files

### ISSUE THREAD

**Issue by Deurnieur** [pinkywafer/Anniversaries#32]
Hi,
  How can I used translations files ?

Thanks

**Comment by pinkywafer** [comment]
The translation files are used for the configuration popups from the integrations page. The language displayed will be the same as the rest of home-assistant (and can be changed on the user settings by clicking on your username in the side panel)

If you mean the 'days' unit of measurement,  then this is not translatable - See the [Notes on unit of measurement section of the readme](https://github.com/pinkywafer/Anniversaries/blob/master/README.md#notes-about-unit-of-measurement)
