### ISSUE TITLE
Integration screen

### ISSUE THREAD

**Issue by twochannel** [pinkywafer/Anniversaries#33]
When using the integration method for configuration dates, each date is its own line in the configuration screen. It would benice if this worked like other integrations where each date was just an icon on the line. (like mqtt, ecobee, etc)

**Comment by pinkywafer** [comment]
Sadly,  this is not possible at the moment. The integrations page was intended for configuring devices (mqtt being a good example - the mqtt integration only configures the broker connection) the configuration for individual sensors is then configured by the devices themselves. A similar thing could be achieved by a purely sensor integration,  but would require a different way of configuring each sensor (ie configuration file).

At this time,  I do not intend to change the way the configuration works. This method is the most convenient for easy configuration and is also in line with the 'built in' components (see certificate expiry for an example of an integration that configures an individual sensor.)

If anything changes in this regard,  I will look at this again.

**Comment by twochannel** [comment]
Thanks for the quick reply!
