### ISSUE TITLE
Half Anniversary Attributes

### ISSUE THREAD

**Issue by twochannel** [pinkywafer/Anniversaries#34]
Your integration has been very helpful, thank you for creating and sharing it.

I have a few things for your consideration I wanted to share.

I've been researching how to do this w/ a template in a card but I can't seem to find a straight forward way to do it with the custom cards I've looked into.  

[secondaryinfo-entity-row](https://github.com/custom-cards/secondaryinfo-entity-row) Doesn't support jinaj2 templates or timestamp formatting
[lovelace-multiple-entity-row](https://github.com/benct/lovelace-multiple-entity-row) Didn't allow me to combine multiple attributes/text on a a row

I have not gone down the path of the other custom card/custom entity value cards yet.  The above is about as far as I was wanting to go down the custom card rabbit hole.

That said, what I am trying to do is

1. Calculate and display info about the half-birthday for a birthday (days-til, date of).  (We look for any opportunity to eat more cake).  Its simply 6 months before the actual birthday. 
2. Show the day of the week for the coming date. 

I could spawn a template sensor and calculate these in the new entity but I felt others could benefit from them being included. And I try to avoid chains of entities.

In addition to your card I display similar info for upcoming events in my google calendar.  For that I used a template sensor to calculate and expose the days-til and then schedule a daily automation to update. If you were looking for other enhancements perhaps there's a way you can refer to an existing sensor to create your sensors in addition to your native events.

Thanks!

**Comment by pinkywafer** [comment]
I should be able to add these as attributes

**Comment by twochannel** [comment]
That'd be great! I'm happy to test if you have a dev branch or similar.

**Comment by pinkywafer** [comment]
Thanks. I'll let you know when I've got something available

**Comment by pinkywafer** [comment]
You can try the Dev branch.  Note that this cannot be installed through hacs and will need to be installed manually

**Comment by twochannel** [comment]
Thanks!

Couple observations for the half-birthday part of the request.


- Had to create a new entry so the half-date option could be selected and populated. I can recreate my entries but wanted to share what I saw.
- The half-date itself is just 6 months prior, but on the same date.  This may not be technically 'half' in terms of days.  e.g. If today- 3/23 was a someone's birthday, their half-birthday would be sept 23rd.   And because nothing is every easy -   feb 29 will be fun :)

**Comment by pinkywafer** [comment]
* you shouldn't need to re-create the entities, You should be able to enable the half option.  Go to the config, integrations page. click on the entry you wish to enable the half options, clich the gear in the top right and turn it on.
* I'd worked on 183 days before... 6 months would pose lots of other issues, eg, 6 months before December 31st would be June 31st  I'm not sure how this could be addressed!

**Comment by pinkywafer** [comment]
maybe original date + 183 days may be better? but the dates would never line up perfectly month to month?

**Comment by twochannel** [comment]
lol! yeah...   Maybe make it a manual/custom field on creation then people can do whatever they want?

**Comment by pinkywafer** [comment]
actually... I think I'm going to have a feb '29th bug anyway... must test that!

what do you suggest? a custom date field? (mm-dd) with date +183 as default?

**Comment by twochannel** [comment]
Well,
The most flexible would be to give the user the ability to add fields with user provided names and values.  For this use case I would create one called half-bday and put a date in. But no calculations would be performed on that date, that way you don't have to worry about month length or leap day.  If a calculated date doesn't work then people wont use it.  Although I'm not sure if anyone else even does this!

Another use case would be weekday, especially if the value could be a jinja2 template.  This way you don't have to code for weekday, users can do just about anything they wanted.  But I dont know enough about how integrations handle data to know if thats possible

The simplest may just to do nothing and let users create a template sensor off yours and they can add their own attributes. This is what I do w/ google calendar entries now.  I dont love it because its another entity to manage.

**Comment by pinkywafer** [comment]
I don't think there's an easy solution to this, other than simply using a template based off the existing. The biggest problem is that the method of defining a half anniversary could mean different things to different people,  so I'm going to leave this out

**Comment by pinkywafer** [comment]
Further thoughts on this... use relativedelta library...

**Comment by pinkywafer** [comment]
@twochannel can you try the latest dev branch please?

**Comment by twochannel** [comment]
nice!   i tested one non-30/31 date and it looks good.  I'm not able to edit an existing entry to toggle feature though.  I'm on 106.6 and I swear It was there on 104.3.  When i click the gear I get the basic entity stuff (override name, disable, and graph).  I also dont see how to delete a entry, either in integrations or entities.
