### ISSUE TITLE
Half Anniversary translations wanted

### ISSUE THREAD

**Issue by pinkywafer** [pinkywafer/Anniversaries#35]
I have added a configuration option.  I would be very grateful if anyone could please supply translations for their languages.
related to: #34

**Comment by pinkywafer** [comment]
holding off on this until config method has been finalised

**Comment by pinkywafer** [comment]
can you guys help please?
@SebRut 
@cherokee93
@Guille-Mas-Coll 
@yuvalabou
@NicolaiVdS 
@kernehed 
@Reconos87

**Comment by NicolaiVdS** [comment]
Sure can

**Comment by cherokee93** [comment]
Sorry for the late reply. Here is the new line, still didn't learn how to PR

`"show_half_anniversary": "Mostra attributo mezzo anniversario"`

**Comment by pinkywafer** [comment]
@cherokee93 thanks I've added manually

**Comment by pinkywafer** [comment]
Still Needed:
`dk.json`
`fr.json`
`nl.json`
