### ISSUE TITLE
help with anniversary announcement

### ISSUE THREAD

**Issue by ranrinc** [pinkywafer/Anniversaries#46]
Hi,

Can someone help me to make an automation, for a general announcement everytime the anniversaries module reach 0?

**Comment by pinkywafer** [comment]
Have a look at my anniversaries config package. There's an automation in each one for an announcement: 
https://github.com/pinkywafer/Home-Assistant_Config/tree/master/packages/anniversaries
Also I think I put an example in my calendarific video:
https://youtu.be/RoqWBJ9IMY4

**Comment by ranrinc** [comment]
@pinkywafer thank you soo much.. its a great help. If I may, quick question, base on your setup.. where should I put my bday information inside the packages? there are no information on where you put it on. Thanks and again sorry for nubie question

**Comment by pinkywafer** [comment]
No problem. If you're not already using packages for your configuration,  the easiest is to take the automation from one of the examples and copy it to your automation.yaml. (The first part of my file configures the sensor, but that is easier to configure on the integrations page) 
If you are using packages,  the arrangement of the files is entirely up to you, the idea is to make your config easy for you to navigate

**Comment by ranrinc** [comment]
Got it.. thanks.. dunno why I miss the anniversary:
