### ISSUE TITLE
Lovelace shows days instead of dage when the UI is set to danish

### ISSUE THREAD

**Issue by fribse** [pinkywafer/Anniversaries#49]
HA VM 0.108.8
Anniversaries is 2.0.3
I have the important days shown in a card with number of days left, and instad of it showing 'dage' in danish, it's showing days.
Is that on purpose or is it a bug, or a setup problem?

**Comment by pinkywafer** [comment]
Sadly the unit_of_measurement (days) is not translatable by home assistant at this time. 
Please see the notes in the readme:
https://github.com/pinkywafer/Anniversaries/blob/master/README.md#notes-about-unit-of-measurement
