### ISSUE TITLE
Configuration.yaml entities appear as anniversaries.anniversary_<name>

### ISSUE THREAD

**Issue by Niconath** [pinkywafer/Anniversaries#64]
Hello since the update 3.0.0 I encounter problems, indeed, it does not show me any more the remaining days but a yellow icon with a triangle in it.
Works in 2.2.0

**Comment by pinkywafer** [comment]
How is your sensor configured?
There was a breaking change in v3.0.0:
If you configured your sensors in configuration.yaml the entity-id will have changed to have the prefix `anniversary_` unless you specify a `id_prefix` of your choice

**Comment by Niconath** [comment]
Yeah, it's in the configuration.  Yaml

So I have to add the prefix anniversarie_ to all the entities for it to work?

Thank you very much for your work and your speed

**Comment by pinkywafer** [comment]
Check your state on the dev page, you should find that they are already prefixed. Just change your Lovelace to point to the new entity_id

**Comment by Niconath** [comment]
Or the how I have to do that, I'm a novice 😕

**Comment by pinkywafer** [comment]
Ok then. If you configured your display in the ui, go to configure ui, then just change the cards where it is displayed. The new names should be on the dropdown

**Comment by Niconath** [comment]
Okay I just saw how to do..., I just changed everything to work perfectly.
Thank you for your speed and help.

**Comment by pinkywafer** [comment]
Actually, I may have just spotted an unintended issue.
I'm getting `anniversaries.anniversary_<<name>> ` from config
And `sensor.anniversary_<<name>>` from ui integrations. 
I'll investigate further later

**Comment by Niconath** [comment]
OK me with anniversaries.anniversary_<<name>> it works fine.

So I should shut it down?

**Comment by pinkywafer** [comment]
It should be under sensor.anniversary_  so it is a bug.
It should work fine as it is, but just beware that the id will change again when I get it fixed

**Comment by Niconath** [comment]
Okay, no problem, but now that you've told me how to do it, I'll know...  Thank you very much. I close the issues?

**Comment by pinkywafer** [comment]
Leave it open, it shows the bug now. I'll rename the issue

**Comment by Niconath** [comment]
Okay, no worries, just let me know when I should close.

Thank you. Have a good day.

**Comment by pinkywafer** [comment]
No problem,  I'll close when fixed

**Comment by Niconath** [comment]
OK 👍
