### ISSUE TITLE
unable to change the date format.

### ISSUE THREAD

**Issue by pippo73** [pinkywafer/Anniversaries#65]
I have a list of BD like this
anniversaries:
  sensors:
  - name: Tommaso Tenconi
    date: '01/10/2019'
    date_format: '%d/%m/%Y'

Could you help me?

is a way to chang the default date tipe?

**Comment by pinkywafer** [comment]
Ah, I see .... The `date_format` option changes the way the date is displayed within the entity in home assistant,  the config must use the format 'yyyy-mm-dd'

**Comment by pippo73** [comment]
AH, ok.
I'm sorry to hear it, but thank you for the answare. I will change all the list.
