### ISSUE TITLE
Calendar Panel integration

### ISSUE THREAD

**Issue by RoldyBuffalo** [pinkywafer/Anniversaries#67]
Sorry, Fat fingered the enter key when typing out the ticket.

But I saw that hassio has a new calendar panel in which my garbage collection has already integrated, wondering if it's possible to integrate this into, that so to speak?

Cheers.

**Comment by pinkywafer** [comment]
Should be possible to add this

**Comment by Vedeneb** [comment]
Bump!

**Comment by jjanderson** [comment]
Bump! Bump!

**Comment by JCHH2** [comment]
bump?

**Comment by pinkywafer** [comment]
Initial support coming soon
