### ISSUE TITLE
Error in years 

### ISSUE THREAD

**Issue by frpaulsen** [pinkywafer/Anniversaries#75]
You need to add 1 to the years

years at next anniversary 59
current years 58
date 19/05 1961
weeks remaining -3097
half anniversary date 19/11 1961
days until half anniversary 0

**Comment by pinkywafer** [comment]
Took me a while to find this.  Testing shows this is when counting UP from an event configured as a one-time event.  I'll investigate the one-time event code

**Comment by frpaulsen** [comment]
Looks good now. Thank you
